package orionedutech.`in`.lmstrainerapp.network

object Urls {
    const val loginUrl = "https://orionedutech.co.in/cglms_app_demo/applogin"
    const val batchUrl = "https://orionedutech.co.in/cglms_app_demo/apptrainerbatches"
    const val courseUrl = "https://orionedutech.co.in/cglms_app_demo/apptrainerbatchcourses"
    const val assignmentUrl = "https://orionedutech.co.in/cglms_app_demo/apptassignments"
    const val dashboardUrl = "https://orionedutech.co.in/cglms_app_demo/apptdashboard"
    const val passwordUpdateUrl = "https://orionedutech.co.in/cglms_app_demo/apppass"
    const val manualUrl = "https://orionedutech.co.in/cglms_app_demo/appmanual"
    const val feedbackUrl = "https://orionedutech.co.in/cglms_app_demo/appfeedbackqns"
    const val feedbackPostUrl = "https://orionedutech.co.in/cglms_app_demo/appfeedbacks"
    const val assessmentUrl = "https://orionedutech.co.in/cglms_app_demo/apptrainerassesments"
    const val assessmentQuestionsUrl = "https://orionedutech.co.in/cglms_app_demo/appassesmentsdata"
    const val assessmentAnsSubmit = "https://orionedutech.co.in/cglms_app_demo/appassesmentsdatasend"
    const val scoreList = "https://orionedutech.co.in/cglms_app_demo/appscorecards"
    const val scoreDetailList = "https://orionedutech.co.in/cglms_app_demo/appscorecard"
    const val batchesUrl = "https://orionedutech.co.in/cglms_app_demo/apptrainerbatcheslist"
    const val assignmentUploadUrl = "https://orionedutech.co.in/cglms_app_demo/apptrainerassignup"
    const val assignmentStudentList = "https://orionedutech.co.in/cglms_app_demo/apptrainerassignstdlist"
    const val assignmentListByBatchAndStudent = "https://orionedutech.co.in/cglms_app_demo/appstrainerassignlist"
    const val assignmentMarksUpload = "https://orionedutech.co.in/cglms_app_demo/appstrainerassignmarks"
    const val courseLinkedModules = "https://orionedutech.co.in/cglms_app_demo/appscourslinks"
    const val moduleLinkedChapters = "https://orionedutech.co.in/cglms_app_demo/appscoursemodulelinks"
    const val studentListUrl = "https://orionedutech.co.in/cglms_app_demo/appgetbatchstudents"
    const val studentAttendanceSubmitUrl = "https://orionedutech.co.in/cglms_app_demo/apptaddattendance"
    const val trainingContent = "https://orionedutech.co.in/cglms_app_demo/apptrainigdata"
    const val subunitUrl = "https://orionedutech.co.in/cglms_app_demo/apptcoursesubunits"
    const val trainingActivity = "https://orionedutech.co.in/cglms_app_demo/apptcoursechapteractivities"
    const val usageData = "https://orionedutech.co.in/cglms_app_demo/appuserstats"
}
